# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
---

- name: Flush IPv4 routes
  become: true
  ansible.posix.sysctl:
    name: 'net.ipv4.route.flush'
    value: 1
    state: present

- name: Flush IPv6 routes
  become: true
  ansible.posix.sysctl:
    name: 'net.ipv6.route.flush'
    value: 1
    state: present
